name: "Standard"
on:
  workflow_call:
  workflow_dispatch:

jobs:
  codespell:
    needs: gap-standard
    uses: Joseph-Edwards/Digraphs/.github/workflows/codespell.yml@ci
  
  lint:
    needs: gap-standard
    strategy:
      fail-fast: false
      matrix:
        linter:
            - gaplint
            - cpplint
    uses: Joseph-Edwards/Digraphs/.github/workflows/lint.yml@ci
    with:
      linter: "${{ matrix.linter }}"
  
  manual:
    needs: gap-standard
    uses: Joseph-Edwards/Digraphs/.github/workflows/manual.yml@ci

  gap-standard:
    name: "${{ matrix.os }}${{ matrix.ABI }}: GAP ${{ matrix.gap-branch }}"
    strategy:
        fail-fast: false
        matrix:
          os:
            - ubuntu
          gap-branch:
            - master
            - stable-4.11
            - stable-4.12
            - stable-4.13
          pkgs-to-clone:
            - NautyTracesInterface
          ABI: ['']
  
          include:
            - gap-branch: stable-4.10
              os: ubuntu
            - gap-branch: master
              pkgs-to-clone: "NautyTracesInterface"
              os: macos
            - gap-branch: master
              os: ubuntu
              ABI: 32
    uses: Joseph-Edwards/Digraphs/.github/workflows/gap_standard.yml@ci
    with:
      os: ${{ matrix.os }}
      gap-branch: ${{ matrix.gap-branch }}
      pkgs-to-clone: ${{ matrix.pkgs-to-clone }}
      ABI: ${{ matrix.ABI }}


  