name: "GAP"
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      gap-branch:
        required: true
        type: string
      pkgs-to-clone:
        required: true
        type: string
      ABI:
        required: false
        type: string
        default: ''

env:
  DIGRAPHS_LIB: digraphs-lib-0.6

jobs:
  tests:
    runs-on: "${{ inputs.os }}-latest"
    steps:
      - uses: actions/checkout@v4
      - name: "Install dependencies"
        if: ${{ runner.os == 'macOS' }}
        run: brew install automake
      - name: "Install GAP and clone/compile necessary packages"
        uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_CLONE: "${{ inputs.pkgs-to-clone }}"
          GAP_PKGS_TO_BUILD: "io orb profiling grape NautyTracesInterface datastructures"
          GAPBRANCH: ${{ inputs.gap-branch }}
          ABI: ${{ inputs.ABI }}
      - name: "Build Digraphs"
        uses: gap-actions/build-pkg@v1
        with:
          ABI: ${{ inputs.ABI }}
      - name: "Install digraphs-lib"
        run: |
          curl --retry 5 -L -O "https://digraphs.github.io/Digraphs/${{ env.DIGRAPHS_LIB }}.tar.gz"
          tar xf "${{ env.DIGRAPHS_LIB }}.tar.gz"
      - name: "Clone datastructures v0.3.0"
        run: |
          if [ ! -d $HOME/gap/pkg/datastructures ]; then
            cd $HOME/gap/pkg/
            git clone https://github.com/gap-packages/datastructures.git datastructures
            cd datastructures
            git checkout v0.3.0
            ./configure
            make
          fi
      - name: "Run DigraphsTestInstall"
        uses: gap-actions/run-pkg-tests@v2
        with:
          GAP_TESTFILE: "tst/github_actions/install.g"
      - name: "Run DigraphsTestStandard"
        uses: gap-actions/run-pkg-tests@v2
        with:
          GAP_TESTFILE: "tst/github_actions/standard.g"
      - name: "Run DigraphsTestManualExamples"
        uses: gap-actions/run-pkg-tests@v2
        with:
          GAP_TESTFILE: "tst/github_actions/examples.g"
      - name: "Run DigraphsTestExtreme"
        uses: gap-actions/run-pkg-tests@v2
        with:
          GAP_TESTFILE: "tst/github_actions/extreme.g"
      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v3
