name: "Lint"
on:
  workflow_dispatch:
    inputs:
      linter:
        required: true
        type: string
        default: 'gaplint'
  workflow_call:
    inputs:
      linter:
        required: true
        type: string

jobs:
  lint:
    name: "${{ inputs.linter }}"
    runs-on: ubuntu-latest
    steps:
    - name: "Check out the repository"
      uses: actions/checkout@v4
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: "Install dependencies with pip"
      run: pip install setuptools
    - name: "Install ${{ inputs.linter }} with pip"
      run: pip install ${{ inputs.linter }}
    - name: "Run ${{ inputs.linter }} on the Digraphs package"
      run: bash etc/${{ inputs.linter }}.sh

