name: "Lint"
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      linter:
        required: true
        type: string
  schedule:
    # Every day at 3:30 AM UTC
    - cron: '30 3 * * *'

jobs:
  lint:
    name: "${{ github.event_name == 'workflow_call' && inputs.linter || 'gaplint' }}"
    runs-on: ubuntu-latest
    steps:
    - name: "Check out the repository"
      uses: actions/checkout@v4
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: "Install dependencies with pip"
      run: pip install setuptools
    - name: "Install ${{ inputs.linter }} with pip"
      run: pip install ${{ github.event_name == 'workflow_call' && inputs.linter || 'gaplint' }}
    - name: "Run ${{ inputs.linter }} on the Digraphs package"
      run: bash etc/${{ github.event_name == 'workflow_call' && inputs.linter || 'gaplint' }}.sh

