name: "PR"
on:
  pull_request:
  push:
    branches:
      - main
      - stable-*.*

jobs:
  codespell:
    uses: Joseph-Edwards/Digraphs/.github/workflows/codespell.yml@ci
  
  lint:
    needs: codespell
    strategy:
      fail-fast: false
      matrix:
        linter:
            - gaplint
            - cpplint
    uses: Joseph-Edwards/Digraphs/.github/workflows/lint.yml@ci
    with:
      linter: "${{ matrix.linter }}"
  
  manual:
    needs: codespell
    uses: Joseph-Edwards/Digraphs/.github/workflows/manual.yml@ci

  gap:
    needs: lint
    name: "${{ matrix.os }}${{ matrix.ABI }} / GAP ${{ matrix.gap-branch }}"
    strategy:
        fail-fast: false
        matrix:
          os:
            - ubuntu
          gap-branch:
            - master
            - stable-4.11
            - stable-4.12
            - stable-4.13
          pkgs-to-clone:
            - NautyTracesInterface
          ABI: ['']
  
          include:
            - gap-branch: stable-4.10
              os: ubuntu
            - gap-branch: master
              pkgs-to-clone: "NautyTracesInterface"
              os: macos
            - gap-branch: master
              os: ubuntu
              ABI: 32
    uses: Joseph-Edwards/Digraphs/.github/workflows/gap.yml@ci
    with:
      os: ${{ matrix.os }}
      gap-branch: ${{ matrix.gap-branch }}
      pkgs-to-clone: ${{ matrix.pkgs-to-clone }}
      ABI: ${{ matrix.ABI }}

  cygwin:
    needs: lint
    uses: Joseph-Edwards/Digraphs/.github/workflows/cygwin.yml@ci

  bliss:
    needs: lint
    uses: Joseph-Edwards/Digraphs/.github/workflows/external_planarity_bliss.yml@ci
    
  valgrind:
    needs: gap
    name: "ubuntu${{ matrix.ABI }} / GAP ${{ matrix.gap-branch }}"
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - master
          - stable-4.11
          - stable-4.12
          - stable-4.13
        pkgs-to-clone:
          - NautyTracesInterface
        ABI: ['']

        include:
          - gap-branch: stable-4.10
          - gap-branch: master
            ABI: 32
    uses: Joseph-Edwards/Digraphs/.github/workflows/valgrind.yml@ci


  