name: "PR"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - stable-*.*
  schedule:
    # Every day at 3:30 AM UTC
    - cron: '30 3 * * *'

jobs:
  first:
    uses: Joseph-Edwards/Digraphs/.github/workflows/first_group.yml@ci
  
  second:
    needs: first
    uses: Joseph-Edwards/Digraphs/.github/workflows/second_group.yml@ci