name: "Extreme"
on:
  workflow_call:
  workflow_dispatch:

jobs:
  gap-extreme:
    name: "${{ matrix.os }}${{ matrix.ABI }}: GAP ${{ matrix.gap-branch }}"
    strategy:
        fail-fast: false
        matrix:
          os:
            - ubuntu
          gap-branch:
            - master
            - stable-4.11
            - stable-4.12
            - stable-4.13
          pkgs-to-clone:
            - NautyTracesInterface
          ABI: ['']
  
          include:
            - gap-branch: stable-4.10
              os: ubuntu
            - gap-branch: master
              pkgs-to-clone: "NautyTracesInterface"
              os: macos
            - gap-branch: master
              os: ubuntu
              ABI: 32
    uses: Joseph-Edwards/Digraphs/.github/workflows/gap_extreme.yml@ci
    with:
      os: ${{ matrix.os }}
      gap-branch: ${{ matrix.gap-branch }}
      pkgs-to-clone: ${{ matrix.pkgs-to-clone }}
      ABI: ${{ matrix.ABI }}

  cygwin:
    name: "cygwin: GAP master"
    uses: Joseph-Edwards/Digraphs/.github/workflows/cygwin.yml@ci

  bliss:
    uses: Joseph-Edwards/Digraphs/.github/workflows/external_planarity_bliss.yml@ci
    
  valgrind:
    name: "ubuntu: GAP ${{ matrix.gap-branch }}"
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - stable-4.13
        pkgs-to-clone:
          - NautyTracesInterface
    uses: Joseph-Edwards/Digraphs/.github/workflows/valgrind.yml@ci
    with:
      gap-branch: ${{ matrix.gap-branch }}
      pkgs-to-clone: ${{ matrix.pkgs-to-clone }}


  