name: "Valgrind"
on:
  workflow_dispatch:
    inputs:
      gap-branch:
        required: true
        type: string
        default: master
      pkgs-to-clone:
        required: true
        type: string
        default: NautyTracesInterface
      ABI:
        required: false
        type: string
        default: ''
  workflow_call:
    inputs:
      gap-branch:
        required: true
        type: string
      pkgs-to-clone:
        required: true
        type: string
      ABI:
        required: false
        type: string
        default: ''

jobs:
  test-valgrind:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: "Install Valgrind"
        run: sudo apt-get install valgrind
      - name: "Install GAP and clone/compile necessary packages"
        uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_CLONE: "${{ inputs.pkgs-to-clone }}"
          GAP_PKGS_TO_BUILD: "io orb profiling grape NautyTracesInterface datastructures"
          GAPBRANCH: ${{ inputs.gap-branch }}
          ABI: ${{ inputs.ABI }}
          CONFIGFLAGS: "--enable-valgrind"
      - name: "Build Digraphs"
        uses: gap-actions/build-pkg@v1
        with:
          ABI: ${{ inputs.ABI }}
      - name: "Clone datastructures v0.3.0"
        run: |
          if [ ! -d $HOME/gap/pkg/datastructures ]; then
            cd $HOME/gap/pkg/
            git clone https://github.com/gap-packages/datastructures.git datastructures
            cd datastructures
            git checkout v0.3.0
            ./configure
            make
          fi
      - name: "Run DigraphsTestInstall"
        uses: gap-actions/run-pkg-tests@v2
        with:
          GAP_TESTFILE: "tst/github_actions/install.g"
          NO_COVERAGE: 'true' 
      - name: "Run DigraphsTestStandard"
        uses: gap-actions/run-pkg-tests@v2
        with:
          GAP_TESTFILE: "tst/github_actions/standard.g"
          NO_COVERAGE: 'true' 
